//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsLauncher.UI.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsLauncher.UI.Properties.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ запрещен.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все категории.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно запущено {0}.
        /// </summary>
        public static string AppLaunchedSuccessfully {
            get {
                return ResourceManager.GetString("AppLaunchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка запуска {0}: {1}.
        /// </summary>
        public static string AppLaunchError {
            get {
                return ResourceManager.GetString("AppLaunchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось запустить {0}: {1}.
        /// </summary>
        public static string AppLaunchFailed {
            get {
                return ResourceManager.GetString("AppLaunchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение запущено: {0}.
        /// </summary>
        public static string ApplicationLaunched {
            get {
                return ResourceManager.GetString("ApplicationLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на приложений.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложения успешно загружены.
        /// </summary>
        public static string ApplicationsLoaded {
            get {
                return ResourceManager.GetString("ApplicationsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложения обновлены.
        /// </summary>
        public static string ApplicationsRefreshed {
            get {
                return ResourceManager.GetString("ApplicationsRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на прил..
        /// </summary>
        public static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корпоративный лаунчер KDV.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аутентификация....
        /// </summary>
        public static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка аутентификации: {0}.
        /// </summary>
        public static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Калькулятор Windows.
        /// </summary>
        public static string CalculatorDescription {
            get {
                return ResourceManager.GetString("CalculatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категории загружены.
        /// </summary>
        public static string CategoriesLoaded {
            get {
                return ResourceManager.GetString("CategoriesLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бизнес.
        /// </summary>
        public static string Category_Business {
            get {
                return ResourceManager.GetString("Category_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коммуникации.
        /// </summary>
        public static string Category_Communication {
            get {
                return ResourceManager.GetString("Category_Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разработка.
        /// </summary>
        public static string Category_Development {
            get {
                return ResourceManager.GetString("Category_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утилиты.
        /// </summary>
        public static string Category_Utilities {
            get {
                return ResourceManager.GetString("Category_Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string CategoryAll {
            get {
                return ResourceManager.GetString("CategoryAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разработка.
        /// </summary>
        public static string CategoryDevelopment {
            get {
                return ResourceManager.GetString("CategoryDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игры.
        /// </summary>
        public static string CategoryGames {
            get {
                return ResourceManager.GetString("CategoryGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Графика.
        /// </summary>
        public static string CategoryGraphics {
            get {
                return ResourceManager.GetString("CategoryGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Медиа.
        /// </summary>
        public static string CategoryMedia {
            get {
                return ResourceManager.GetString("CategoryMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Офис.
        /// </summary>
        public static string CategoryOffice {
            get {
                return ResourceManager.GetString("CategoryOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Безопасность.
        /// </summary>
        public static string CategorySecurity {
            get {
                return ResourceManager.GetString("CategorySecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Система.
        /// </summary>
        public static string CategorySystem {
            get {
                return ResourceManager.GetString("CategorySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструменты.
        /// </summary>
        public static string CategoryTools {
            get {
                return ResourceManager.GetString("CategoryTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Веб.
        /// </summary>
        public static string CategoryWeb {
            get {
                return ResourceManager.GetString("CategoryWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Командная строка Windows.
        /// </summary>
        public static string CommandPromptDescription {
            get {
                return ResourceManager.GetString("CommandPromptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        public static string Common_About {
            get {
                return ResourceManager.GetString("Common_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        public static string Common_Filter {
            get {
                return ResourceManager.GetString("Common_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        public static string Common_Help {
            get {
                return ResourceManager.GetString("Common_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОК.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string Common_Settings {
            get {
                return ResourceManager.GetString("Common_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка конфигурации: {0}.
        /// </summary>
        public static string ConfigurationError {
            get {
                return ResourceManager.GetString("ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите выйти?.
        /// </summary>
        public static string ConfirmLogout {
            get {
                return ResourceManager.GetString("ConfirmLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить как текущий пользователь.
        /// </summary>
        public static string ContinueAsCurrentUser {
            get {
                return ResourceManager.GetString("ContinueAsCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель управления Windows.
        /// </summary>
        public static string ControlPanelDescription {
            get {
                return ResourceManager.GetString("ControlPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий пользователь Windows:.
        /// </summary>
        public static string CurrentWindowsUser {
            get {
                return ResourceManager.GetString("CurrentWindowsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка базы данных: {0}.
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на База данных успешно инициализирована.
        /// </summary>
        public static string DatabaseInitialized {
            get {
                return ResourceManager.GetString("DatabaseInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инициализация базы данных....
        /// </summary>
        public static string DatabaseInitializing {
            get {
                return ResourceManager.GetString("DatabaseInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на База данных готова.
        /// </summary>
        public static string DatabaseReady {
            get {
                return ResourceManager.GetString("DatabaseReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ запрещен.
        /// </summary>
        public static string Error_AccessDenied {
            get {
                return ResourceManager.GetString("Error_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка.
        /// </summary>
        public static string Error_CriticalError {
            get {
                return ResourceManager.GetString("Error_CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на База данных недоступна.
        /// </summary>
        public static string Error_DatabaseUnavailable {
            get {
                return ResourceManager.GetString("Error_DatabaseUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детали: {0}.
        /// </summary>
        public static string Error_Details {
            get {
                return ResourceManager.GetString("Error_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Домен недоступен.
        /// </summary>
        public static string Error_DomainUnavailable {
            get {
                return ResourceManager.GetString("Error_DomainUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка.
        /// </summary>
        public static string Error_General {
            get {
                return ResourceManager.GetString("Error_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверные учетные данные.
        /// </summary>
        public static string Error_InvalidCredentials {
            get {
                return ResourceManager.GetString("Error_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сеть недоступна.
        /// </summary>
        public static string Error_NetworkUnavailable {
            get {
                return ResourceManager.GetString("Error_NetworkUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка запуска.
        /// </summary>
        public static string Error_StartupError {
            get {
                return ResourceManager.GetString("Error_StartupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось запустить приложение:\n\n{0}.
        /// </summary>
        public static string Error_StartupFailed {
            get {
                return ResourceManager.GetString("Error_StartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла непредвиденная ошибка:\n\n{0}\n\nПриложение будет закрыто..
        /// </summary>
        public static string Error_UnhandledException {
            get {
                return ResourceManager.GetString("Error_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не найден.
        /// </summary>
        public static string Error_UserNotFound {
            get {
                return ResourceManager.GetString("Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ запрещен. Проверьте ваши права доступа..
        /// </summary>
        public static string ErrorAccessDenied {
            get {
                return ResourceManager.GetString("ErrorAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предоставлены недопустимые данные..
        /// </summary>
        public static string ErrorInvalidData {
            get {
                return ResourceManager.GetString("ErrorInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимая операция..
        /// </summary>
        public static string ErrorInvalidOperation {
            get {
                return ResourceManager.GetString("ErrorInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки приложений: {0}.
        /// </summary>
        public static string ErrorLoadingApplications {
            get {
                return ResourceManager.GetString("ErrorLoadingApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время ожидания операции истекло. Попробуйте снова..
        /// </summary>
        public static string ErrorTimeout {
            get {
                return ResourceManager.GetString("ErrorTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла неизвестная ошибка.
        /// </summary>
        public static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось запустить {0}: {1}.
        /// </summary>
        public static string FailedToLaunch {
            get {
                return ResourceManager.GetString("FailedToLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проводник Windows.
        /// </summary>
        public static string FileExplorerDescription {
            get {
                return ResourceManager.GetString("FileExplorerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтрация приложений....
        /// </summary>
        public static string FilteringApplications {
            get {
                return ResourceManager.GetString("FilteringApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск Google.
        /// </summary>
        public static string GoogleDescription {
            get {
                return ResourceManager.GetString("GoogleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение....
        /// </summary>
        public static string Info_Connecting {
            get {
                return ResourceManager.GetString("Info_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка....
        /// </summary>
        public static string Info_Loading {
            get {
                return ResourceManager.GetString("Info_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработка....
        /// </summary>
        public static string Info_Processing {
            get {
                return ResourceManager.GetString("Info_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение....
        /// </summary>
        public static string Info_Saving {
            get {
                return ResourceManager.GetString("Info_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка инициализации: {0}.
        /// </summary>
        public static string InitializationError {
            get {
                return ResourceManager.GetString("InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инициализация....
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка запуска.
        /// </summary>
        public static string LaunchError {
            get {
                return ResourceManager.GetString("LaunchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск {0}....
        /// </summary>
        public static string LaunchingApp {
            get {
                return ResourceManager.GetString("LaunchingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружено {0} приложений.
        /// </summary>
        public static string LoadedApps {
            get {
                return ResourceManager.GetString("LoadedApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка приложений....
        /// </summary>
        public static string LoadingApplications {
            get {
                return ResourceManager.GetString("LoadingApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход выполнен.
        /// </summary>
        public static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполняется аутентификация....
        /// </summary>
        public static string LoginWindow_Authenticating {
            get {
                return ResourceManager.GetString("LoginWindow_Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аутентификация в домене....
        /// </summary>
        public static string LoginWindow_AuthenticatingDomain {
            get {
                return ResourceManager.GetString("LoginWindow_AuthenticatingDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аутентификация сервисного администратора....
        /// </summary>
        public static string LoginWindow_AuthenticatingService {
            get {
                return ResourceManager.GetString("LoginWindow_AuthenticatingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка домена....
        /// </summary>
        public static string LoginWindow_CheckingDomain {
            get {
                return ResourceManager.GetString("LoginWindow_CheckingDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Домен.
        /// </summary>
        public static string LoginWindow_Domain {
            get {
                return ResourceManager.GetString("LoginWindow_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Домен доступен.
        /// </summary>
        public static string LoginWindow_DomainAvailable {
            get {
                return ResourceManager.GetString("LoginWindow_DomainAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доменный вход.
        /// </summary>
        public static string LoginWindow_DomainMode {
            get {
                return ResourceManager.GetString("LoginWindow_DomainMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Домен недоступен.
        /// </summary>
        public static string LoginWindow_DomainUnavailable {
            get {
                return ResourceManager.GetString("LoginWindow_DomainUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string LoginWindow_Login {
            get {
                return ResourceManager.GetString("LoginWindow_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string LoginWindow_Password {
            get {
                return ResourceManager.GetString("LoginWindow_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запомнить учетные данные.
        /// </summary>
        public static string LoginWindow_RememberCredentials {
            get {
                return ResourceManager.GetString("LoginWindow_RememberCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервисный администратор.
        /// </summary>
        public static string LoginWindow_ServiceMode {
            get {
                return ResourceManager.GetString("LoginWindow_ServiceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль администратора.
        /// </summary>
        public static string LoginWindow_ServicePassword {
            get {
                return ResourceManager.GetString("LoginWindow_ServicePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя сервисного администратора.
        /// </summary>
        public static string LoginWindow_ServiceUsername {
            get {
                return ResourceManager.GetString("LoginWindow_ServiceUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string LoginWindow_Settings {
            get {
                return ResourceManager.GetString("LoginWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корпоративный лаунчер приложений KDV.
        /// </summary>
        public static string LoginWindow_Subtitle {
            get {
                return ResourceManager.GetString("LoginWindow_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход в систему.
        /// </summary>
        public static string LoginWindow_Title {
            get {
                return ResourceManager.GetString("LoginWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя.
        /// </summary>
        public static string LoginWindow_Username {
            get {
                return ResourceManager.GetString("LoginWindow_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корпоративный лаунчер KDV - Вход.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка выхода: {0}.
        /// </summary>
        public static string LogoutError {
            get {
                return ResourceManager.GetString("LogoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти из приложения.
        /// </summary>
        public static string LogoutTooltip {
            get {
                return ResourceManager.GetString("LogoutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корпоративный лаунчер KDV.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложения не найдены.
        /// </summary>
        public static string NoApplicationsFound {
            get {
                return ResourceManager.GetString("NoApplicationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попробуйте изменить поиск или фильтр категории.
        /// </summary>
        public static string NoApplicationsHint {
            get {
                return ResourceManager.GetString("NoApplicationsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текстовый редактор.
        /// </summary>
        public static string NotepadDescription {
            get {
                return ResourceManager.GetString("NotepadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Или войти с другими учетными данными:.
        /// </summary>
        public static string OrSignInDifferent {
            get {
                return ResourceManager.GetString("OrSignInDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор Paint.
        /// </summary>
        public static string PaintDescription {
            get {
                return ResourceManager.GetString("PaintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, введите пароль.
        /// </summary>
        public static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, введите имя пользователя.
        /// </summary>
        public static string PleaseEnterUsername {
            get {
                return ResourceManager.GetString("PleaseEnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готов.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить приложения.
        /// </summary>
        public static string RefreshTooltip {
            get {
                return ResourceManager.GetString("RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор реестра Windows.
        /// </summary>
        public static string RegistryEditorDescription {
            get {
                return ResourceManager.GetString("RegistryEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        public static string RoleAdministrator {
            get {
                return ResourceManager.GetString("RoleAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опытный пользователь.
        /// </summary>
        public static string RolePowerUser {
            get {
                return ResourceManager.GetString("RolePowerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стандартный.
        /// </summary>
        public static string RoleStandard {
            get {
                return ResourceManager.GetString("RoleStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск приложений....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сервиса: {0}.
        /// </summary>
        public static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция настроек скоро будет доступна....
        /// </summary>
        public static string SettingsComingSoon {
            get {
                return ResourceManager.GetString("SettingsComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string SettingsTooltip {
            get {
                return ResourceManager.GetString("SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окно настроек будет реализовано в следующей итерации..
        /// </summary>
        public static string SettingsWindowMessage {
            get {
                return ResourceManager.GetString("SettingsWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение запущено.
        /// </summary>
        public static string Success_ApplicationLaunched {
            get {
                return ResourceManager.GetString("Success_ApplicationLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход выполнен успешно.
        /// </summary>
        public static string Success_LoginCompleted {
            get {
                return ResourceManager.GetString("Success_LoginCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки сохранены.
        /// </summary>
        public static string Success_SettingsSaved {
            get {
                return ResourceManager.GetString("Success_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно запущено {0}.
        /// </summary>
        public static string SuccessfullyLaunched {
            get {
                return ResourceManager.GetString("SuccessfullyLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переключено на пользователя: {0}.
        /// </summary>
        public static string SwitchedToUser {
            get {
                return ResourceManager.GetString("SwitchedToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сменить пользователя.
        /// </summary>
        public static string SwitchUser {
            get {
                return ResourceManager.GetString("SwitchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка смены пользователя: {0}.
        /// </summary>
        public static string SwitchUserError {
            get {
                return ResourceManager.GetString("SwitchUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переключиться на другого пользователя.
        /// </summary>
        public static string SwitchUserTooltip {
            get {
                return ResourceManager.GetString("SwitchUserTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диспетчер задач Windows.
        /// </summary>
        public static string TaskManagerDescription {
            get {
                return ResourceManager.GetString("TaskManagerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка времени ожидания.
        /// </summary>
        public static string TimeoutError {
            get {
                return ResourceManager.GetString("TimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь успешно аутентифицирован.
        /// </summary>
        public static string UserAuthenticated {
            get {
                return ResourceManager.GetString("UserAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка данных пользователя....
        /// </summary>
        public static string UserDataLoading {
            get {
                return ResourceManager.GetString("UserDataLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя:.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуется режим сервисного администратора.
        /// </summary>
        public static string Warning_ServiceModeRequired {
            get {
                return ResourceManager.GetString("Warning_ServiceModeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас есть несохраненные изменения.
        /// </summary>
        public static string Warning_UnsavedChanges {
            get {
                return ResourceManager.GetString("Warning_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать, {0}!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать, {0}!.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корпоративный лаунчер KDV - {0} ({1}).
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор WordPad.
        /// </summary>
        public static string WordpadDescription {
            get {
                return ResourceManager.GetString("WordpadDescription", resourceCulture);
            }
        }
    }
}
