//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsLauncher.UI.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsLauncher.UI.Properties.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Categories.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KDV Corporate Launcher.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authenticating....
        /// </summary>
        public static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Calculator.
        /// </summary>
        public static string CalculatorDescription {
            get {
                return ResourceManager.GetString("CalculatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Business.
        /// </summary>
        public static string Category_Business {
            get {
                return ResourceManager.GetString("Category_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Communication.
        /// </summary>
        public static string Category_Communication {
            get {
                return ResourceManager.GetString("Category_Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Utilities.
        /// </summary>
        public static string Category_Utilities {
            get {
                return ResourceManager.GetString("Category_Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        public static string CategoryAll {
            get {
                return ResourceManager.GetString("CategoryAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Development.
        /// </summary>
        public static string CategoryDevelopment {
            get {
                return ResourceManager.GetString("CategoryDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Office.
        /// </summary>
        public static string CategoryOffice {
            get {
                return ResourceManager.GetString("CategoryOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System.
        /// </summary>
        public static string CategorySystem {
            get {
                return ResourceManager.GetString("CategorySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools.
        /// </summary>
        public static string CategoryTools {
            get {
                return ResourceManager.GetString("CategoryTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web.
        /// </summary>
        public static string CategoryWeb {
            get {
                return ResourceManager.GetString("CategoryWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Command Line.
        /// </summary>
        public static string CommandPromptDescription {
            get {
                return ResourceManager.GetString("CommandPromptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string Common_About {
            get {
                return ResourceManager.GetString("Common_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        public static string Common_Filter {
            get {
                return ResourceManager.GetString("Common_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string Common_Help {
            get {
                return ResourceManager.GetString("Common_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Common_Settings {
            get {
                return ResourceManager.GetString("Common_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to logout?.
        /// </summary>
        public static string ConfirmLogout {
            get {
                return ResourceManager.GetString("ConfirmLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue as current user.
        /// </summary>
        public static string ContinueAsCurrentUser {
            get {
                return ResourceManager.GetString("ContinueAsCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Control Panel.
        /// </summary>
        public static string ControlPanelDescription {
            get {
                return ResourceManager.GetString("ControlPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Windows user:.
        /// </summary>
        public static string CurrentWindowsUser {
            get {
                return ResourceManager.GetString("CurrentWindowsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access denied.
        /// </summary>
        public static string Error_AccessDenied {
            get {
                return ResourceManager.GetString("Error_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Critical Error.
        /// </summary>
        public static string Error_CriticalError {
            get {
                return ResourceManager.GetString("Error_CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database unavailable.
        /// </summary>
        public static string Error_DatabaseUnavailable {
            get {
                return ResourceManager.GetString("Error_DatabaseUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details: {0}.
        /// </summary>
        public static string Error_Details {
            get {
                return ResourceManager.GetString("Error_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Domain unavailable.
        /// </summary>
        public static string Error_DomainUnavailable {
            get {
                return ResourceManager.GetString("Error_DomainUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred.
        /// </summary>
        public static string Error_General {
            get {
                return ResourceManager.GetString("Error_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid credentials.
        /// </summary>
        public static string Error_InvalidCredentials {
            get {
                return ResourceManager.GetString("Error_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network unavailable.
        /// </summary>
        public static string Error_NetworkUnavailable {
            get {
                return ResourceManager.GetString("Error_NetworkUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Startup Error.
        /// </summary>
        public static string Error_StartupError {
            get {
                return ResourceManager.GetString("Error_StartupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to start application:\n\n{0}.
        /// </summary>
        public static string Error_StartupFailed {
            get {
                return ResourceManager.GetString("Error_StartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An unexpected error occurred:\n\n{0}\n\nThe application will be closed..
        /// </summary>
        public static string Error_UnhandledException {
            get {
                return ResourceManager.GetString("Error_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User not found.
        /// </summary>
        public static string Error_UserNotFound {
            get {
                return ResourceManager.GetString("Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Google Search.
        /// </summary>
        public static string GoogleDescription {
            get {
                return ResourceManager.GetString("GoogleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connecting....
        /// </summary>
        public static string Info_Connecting {
            get {
                return ResourceManager.GetString("Info_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading....
        /// </summary>
        public static string Info_Loading {
            get {
                return ResourceManager.GetString("Info_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing....
        /// </summary>
        public static string Info_Processing {
            get {
                return ResourceManager.GetString("Info_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving....
        /// </summary>
        public static string Info_Saving {
            get {
                return ResourceManager.GetString("Info_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initializing....
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading applications....
        /// </summary>
        public static string LoadingApplications {
            get {
                return ResourceManager.GetString("LoadingApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authenticating....
        /// </summary>
        public static string LoginWindow_Authenticating {
            get {
                return ResourceManager.GetString("LoginWindow_Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Domain authentication....
        /// </summary>
        public static string LoginWindow_AuthenticatingDomain {
            get {
                return ResourceManager.GetString("LoginWindow_AuthenticatingDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service administrator authentication....
        /// </summary>
        public static string LoginWindow_AuthenticatingService {
            get {
                return ResourceManager.GetString("LoginWindow_AuthenticatingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking domain....
        /// </summary>
        public static string LoginWindow_CheckingDomain {
            get {
                return ResourceManager.GetString("LoginWindow_CheckingDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Domain.
        /// </summary>
        public static string LoginWindow_Domain {
            get {
                return ResourceManager.GetString("LoginWindow_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Domain available.
        /// </summary>
        public static string LoginWindow_DomainAvailable {
            get {
                return ResourceManager.GetString("LoginWindow_DomainAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Domain Login.
        /// </summary>
        public static string LoginWindow_DomainMode {
            get {
                return ResourceManager.GetString("LoginWindow_DomainMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Domain unavailable.
        /// </summary>
        public static string LoginWindow_DomainUnavailable {
            get {
                return ResourceManager.GetString("LoginWindow_DomainUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string LoginWindow_Login {
            get {
                return ResourceManager.GetString("LoginWindow_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string LoginWindow_Password {
            get {
                return ResourceManager.GetString("LoginWindow_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remember credentials.
        /// </summary>
        public static string LoginWindow_RememberCredentials {
            get {
                return ResourceManager.GetString("LoginWindow_RememberCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service Administrator.
        /// </summary>
        public static string LoginWindow_ServiceMode {
            get {
                return ResourceManager.GetString("LoginWindow_ServiceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Administrator Password.
        /// </summary>
        public static string LoginWindow_ServicePassword {
            get {
                return ResourceManager.GetString("LoginWindow_ServicePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service Administrator Username.
        /// </summary>
        public static string LoginWindow_ServiceUsername {
            get {
                return ResourceManager.GetString("LoginWindow_ServiceUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string LoginWindow_Settings {
            get {
                return ResourceManager.GetString("LoginWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KDV Corporate Application Launcher.
        /// </summary>
        public static string LoginWindow_Subtitle {
            get {
                return ResourceManager.GetString("LoginWindow_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System Login.
        /// </summary>
        public static string LoginWindow_Title {
            get {
                return ResourceManager.GetString("LoginWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username.
        /// </summary>
        public static string LoginWindow_Username {
            get {
                return ResourceManager.GetString("LoginWindow_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KDV Corporate Launcher - Login.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout from application.
        /// </summary>
        public static string LogoutTooltip {
            get {
                return ResourceManager.GetString("LogoutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KDV Corporate Launcher.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text Editor.
        /// </summary>
        public static string NotepadDescription {
            get {
                return ResourceManager.GetString("NotepadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Or sign in with different credentials:.
        /// </summary>
        public static string OrSignInDifferent {
            get {
                return ResourceManager.GetString("OrSignInDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter password.
        /// </summary>
        public static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter username.
        /// </summary>
        public static string PleaseEnterUsername {
            get {
                return ResourceManager.GetString("PleaseEnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh applications.
        /// </summary>
        public static string RefreshTooltip {
            get {
                return ResourceManager.GetString("RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Administrator.
        /// </summary>
        public static string RoleAdministrator {
            get {
                return ResourceManager.GetString("RoleAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power User.
        /// </summary>
        public static string RolePowerUser {
            get {
                return ResourceManager.GetString("RolePowerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard.
        /// </summary>
        public static string RoleStandard {
            get {
                return ResourceManager.GetString("RoleStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search applications....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings feature coming soon....
        /// </summary>
        public static string SettingsComingSoon {
            get {
                return ResourceManager.GetString("SettingsComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsTooltip {
            get {
                return ResourceManager.GetString("SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings window will be implemented in the next iteration..
        /// </summary>
        public static string SettingsWindowMessage {
            get {
                return ResourceManager.GetString("SettingsWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application launched.
        /// </summary>
        public static string Success_ApplicationLaunched {
            get {
                return ResourceManager.GetString("Success_ApplicationLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login completed successfully.
        /// </summary>
        public static string Success_LoginCompleted {
            get {
                return ResourceManager.GetString("Success_LoginCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings saved.
        /// </summary>
        public static string Success_SettingsSaved {
            get {
                return ResourceManager.GetString("Success_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch User.
        /// </summary>
        public static string SwitchUser {
            get {
                return ResourceManager.GetString("SwitchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch to another user.
        /// </summary>
        public static string SwitchUserTooltip {
            get {
                return ResourceManager.GetString("SwitchUserTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username:.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service administrator mode required.
        /// </summary>
        public static string Warning_ServiceModeRequired {
            get {
                return ResourceManager.GetString("Warning_ServiceModeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have unsaved changes.
        /// </summary>
        public static string Warning_UnsavedChanges {
            get {
                return ResourceManager.GetString("Warning_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome, {0}!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KDV Corporate Launcher - {0} ({1}).
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
