-- ===== create_firebird_embedded_v1.0.0.001_FIXED.sql =====
-- Исправленный скрипт для Firebird 5.0 Embedded
-- Для локальных установок с файловой БД
-- Использование: isql -user SYSDBA -password KDV_Launcher_2025! -i create_firebird_embedded_v1.0.0.001_FIXED.sql

-- 1. Создание embedded базы данных
CREATE DATABASE 'C:\WindowsLauncher\Data\launcher_embedded.fdb' 
PAGE_SIZE 8192
USER 'SYSDBA' 
PASSWORD 'KDV_Launcher_2025!'
DEFAULT CHARACTER SET UTF8;

-- Подключение к созданной БД
CONNECT 'C:\WindowsLauncher\Data\launcher_embedded.fdb' 
USER 'SYSDBA' 
PASSWORD 'KDV_Launcher_2025!';

-- ===== СОЗДАНИЕ ТАБЛИЦ С IDENTITY КОЛОНКАМИ =====

-- Таблица пользователей (Firebird 5.0 совместимый синтаксис)
CREATE TABLE USERS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL,
    DISPLAY_NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(255),
    ROLE INTEGER NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    IS_SERVICE_ACCOUNT BOOLEAN NOT NULL,
    PASSWORD_HASH VARCHAR(500),
    SALT VARCHAR(500),
    CREATED_AT TIMESTAMP NOT NULL,
    LAST_LOGIN_AT TIMESTAMP,
    LAST_ACTIVITY_AT TIMESTAMP,
    FAILED_LOGIN_ATTEMPTS INTEGER NOT NULL,
    IS_LOCKED BOOLEAN NOT NULL,
    LOCKOUT_END TIMESTAMP,
    LAST_PASSWORD_CHANGE TIMESTAMP,
    GROUPS_JSON VARCHAR(2000),
    SETTINGS_JSON VARCHAR(4000),
    METADATA_JSON VARCHAR(2000),
    AUTHENTICATION_TYPE INTEGER NOT NULL,
    DOMAIN_USERNAME VARCHAR(100),
    LAST_DOMAIN_SYNC TIMESTAMP,
    IS_LOCAL_USER BOOLEAN NOT NULL,
    ALLOW_LOCAL_LOGIN BOOLEAN NOT NULL,
    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME)
);

-- Таблица приложений
CREATE TABLE APPLICATIONS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(500),
    EXECUTABLE_PATH VARCHAR(1000) NOT NULL,
    ARGUMENTS VARCHAR(500),
    WORKING_DIRECTORY VARCHAR(1000),
    ICON_PATH VARCHAR(1000),
    ICONTEXT VARCHAR(50),
    CATEGORY VARCHAR(100),
    APP_TYPE INTEGER NOT NULL,
    MINIMUM_ROLE INTEGER NOT NULL,
    IS_ENABLED BOOLEAN NOT NULL,
    SORT_ORDER INTEGER NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    MODIFIED_DATE TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(100),
    REQUIRED_GROUPS BLOB SUB_TYPE TEXT
);

-- Таблица настроек пользователей
CREATE TABLE USER_SETTINGS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    THEME VARCHAR(50),
    ACCENT_COLOR VARCHAR(50),
    TILE_SIZE INTEGER,
    SHOW_CATEGORIES BOOLEAN,
    DEFAULT_CATEGORY VARCHAR(100),
    AUTO_REFRESH BOOLEAN,
    REFRESH_INTERVAL_MINUTES INTEGER,
    SHOW_DESCRIPTIONS BOOLEAN,
    HIDDEN_CATEGORIES BLOB SUB_TYPE TEXT,
    LAST_MODIFIED TIMESTAMP NOT NULL,
    CONSTRAINT FK_USER_SETTINGS_USER_ID FOREIGN KEY (USER_ID) 
        REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Таблица аудита
CREATE TABLE AUDIT_LOGS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID INTEGER,
    USERNAME VARCHAR(100) NOT NULL,
    ACTION VARCHAR(100) NOT NULL,
    APPLICATION_NAME VARCHAR(200),
    DETAILS BLOB SUB_TYPE TEXT,
    TIMESTAMP_UTC TIMESTAMP NOT NULL,
    SUCCESS BOOLEAN NOT NULL,
    ERROR_MESSAGE VARCHAR(1000),
    COMPUTER_NAME VARCHAR(100),
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(500),
    METADATA_JSON BLOB SUB_TYPE TEXT,
    CONSTRAINT FK_AUDIT_LOGS_USER_ID FOREIGN KEY (USER_ID) 
        REFERENCES USERS(ID) ON DELETE SET NULL
);

-- Таблица версий БД
CREATE TABLE DATABASE_VERSION (
    VERSION VARCHAR(20) NOT NULL,
    APPLIED_AT TIMESTAMP NOT NULL,
    APPLICATION_VERSION VARCHAR(20),
    CONSTRAINT PK_DATABASE_VERSION PRIMARY KEY (VERSION)
);

-- Таблица истории миграций
CREATE TABLE MIGRATION_HISTORY (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VERSION VARCHAR(20) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION BLOB SUB_TYPE TEXT,
    APPLIED_AT TIMESTAMP NOT NULL,
    ROLLBACK_SCRIPT BLOB SUB_TYPE TEXT
);

-- ===== ДОБАВЛЕНИЕ DEFAULT ЗНАЧЕНИЙ =====
-- Добавляем DEFAULT значения после создания таблиц (совместимость с Firebird 5.0)
ALTER TABLE USERS ALTER COLUMN ROLE SET DEFAULT 2;
ALTER TABLE USERS ALTER COLUMN IS_ACTIVE SET DEFAULT TRUE;
ALTER TABLE USERS ALTER COLUMN IS_SERVICE_ACCOUNT SET DEFAULT FALSE;
ALTER TABLE USERS ALTER COLUMN FAILED_LOGIN_ATTEMPTS SET DEFAULT 0;
ALTER TABLE USERS ALTER COLUMN IS_LOCKED SET DEFAULT FALSE;
ALTER TABLE USERS ALTER COLUMN GROUPS_JSON SET DEFAULT '[]';
ALTER TABLE USERS ALTER COLUMN SETTINGS_JSON SET DEFAULT '{}';
ALTER TABLE USERS ALTER COLUMN METADATA_JSON SET DEFAULT '{}';
ALTER TABLE USERS ALTER COLUMN AUTHENTICATION_TYPE SET DEFAULT 0;
ALTER TABLE USERS ALTER COLUMN IS_LOCAL_USER SET DEFAULT TRUE;
ALTER TABLE USERS ALTER COLUMN ALLOW_LOCAL_LOGIN SET DEFAULT FALSE;

ALTER TABLE APPLICATIONS ALTER COLUMN ICONTEXT SET DEFAULT '📱';
ALTER TABLE APPLICATIONS ALTER COLUMN APP_TYPE SET DEFAULT 1;
ALTER TABLE APPLICATIONS ALTER COLUMN MINIMUM_ROLE SET DEFAULT 2;
ALTER TABLE APPLICATIONS ALTER COLUMN IS_ENABLED SET DEFAULT TRUE;
ALTER TABLE APPLICATIONS ALTER COLUMN SORT_ORDER SET DEFAULT 0;
ALTER TABLE APPLICATIONS ALTER COLUMN REQUIRED_GROUPS SET DEFAULT '[]';

ALTER TABLE USER_SETTINGS ALTER COLUMN THEME SET DEFAULT 'Light';
ALTER TABLE USER_SETTINGS ALTER COLUMN ACCENT_COLOR SET DEFAULT 'Blue';
ALTER TABLE USER_SETTINGS ALTER COLUMN TILE_SIZE SET DEFAULT 150;
ALTER TABLE USER_SETTINGS ALTER COLUMN SHOW_CATEGORIES SET DEFAULT TRUE;
ALTER TABLE USER_SETTINGS ALTER COLUMN DEFAULT_CATEGORY SET DEFAULT 'All';
ALTER TABLE USER_SETTINGS ALTER COLUMN AUTO_REFRESH SET DEFAULT TRUE;
ALTER TABLE USER_SETTINGS ALTER COLUMN REFRESH_INTERVAL_MINUTES SET DEFAULT 30;
ALTER TABLE USER_SETTINGS ALTER COLUMN SHOW_DESCRIPTIONS SET DEFAULT TRUE;
ALTER TABLE USER_SETTINGS ALTER COLUMN HIDDEN_CATEGORIES SET DEFAULT '[]';

ALTER TABLE AUDIT_LOGS ALTER COLUMN SUCCESS SET DEFAULT TRUE;
ALTER TABLE AUDIT_LOGS ALTER COLUMN METADATA_JSON SET DEFAULT '{}';

-- ===== ИНДЕКСЫ =====
CREATE INDEX IDX_USERS_USERNAME ON USERS(USERNAME);
CREATE INDEX IDX_USERS_ROLE ON USERS(ROLE);
CREATE INDEX IDX_USERS_IS_ACTIVE ON USERS(IS_ACTIVE);
CREATE INDEX IDX_USERS_AUTHENTICATION_TYPE ON USERS(AUTHENTICATION_TYPE);

CREATE INDEX IDX_APPLICATIONS_NAME ON APPLICATIONS(NAME);
CREATE INDEX IDX_APPLICATIONS_CATEGORY ON APPLICATIONS(CATEGORY);
CREATE INDEX IDX_APPLICATIONS_IS_ENABLED ON APPLICATIONS(IS_ENABLED);
CREATE INDEX IDX_APPLICATIONS_SORT_ORDER ON APPLICATIONS(SORT_ORDER);

CREATE INDEX IDX_USER_SETTINGS_USER_ID ON USER_SETTINGS(USER_ID);

CREATE INDEX IDX_AUDIT_LOGS_TIMESTAMP_UTC ON AUDIT_LOGS(TIMESTAMP_UTC);
CREATE INDEX IDX_AUDIT_LOGS_USER_ID ON AUDIT_LOGS(USER_ID);
CREATE INDEX IDX_AUDIT_LOGS_ACTION ON AUDIT_LOGS(ACTION);

CREATE INDEX IDX_MIGRATION_HISTORY_VERSION ON MIGRATION_HISTORY(VERSION);

-- ===== НАЧАЛЬНЫЕ ДАННЫЕ =====
INSERT INTO DATABASE_VERSION (VERSION, APPLIED_AT, APPLICATION_VERSION) 
VALUES ('1.0.0.001', CURRENT_TIMESTAMP, '1.0.0');

INSERT INTO MIGRATION_HISTORY (VERSION, NAME, DESCRIPTION, APPLIED_AT) 
VALUES ('1.0.0.001', 'InitialSchema', 'Create initial database schema with all tables and indexes for Firebird 5.0 embedded', CURRENT_TIMESTAMP);

-- Базовый пользователь (guest) для первоначального доступа
INSERT INTO USERS (USERNAME, DISPLAY_NAME, EMAIL, ROLE, IS_ACTIVE, IS_SERVICE_ACCOUNT, 
                   PASSWORD_HASH, SALT, CREATED_AT, AUTHENTICATION_TYPE, DOMAIN_USERNAME, 
                   IS_LOCAL_USER, ALLOW_LOCAL_LOGIN, FAILED_LOGIN_ATTEMPTS, IS_LOCKED, 
                   GROUPS_JSON, SETTINGS_JSON, METADATA_JSON) 
VALUES ('guest', 'Guest User', 'guest@local', 2, TRUE, FALSE, '', '', CURRENT_TIMESTAMP, 
        0, '', TRUE, FALSE, 0, FALSE, '[]', '{}', '{}');

-- Базовые приложения
INSERT INTO APPLICATIONS (NAME, DESCRIPTION, EXECUTABLE_PATH, ICONTEXT, CATEGORY, 
                         APP_TYPE, MINIMUM_ROLE, IS_ENABLED, SORT_ORDER, CREATED_DATE, 
                         MODIFIED_DATE, CREATED_BY, REQUIRED_GROUPS) 
VALUES ('Calculator', 'Windows Calculator', 'calc.exe', '🧮', 'Utilities', 1, 2, TRUE, 1, 
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'System', '[]');

INSERT INTO APPLICATIONS (NAME, DESCRIPTION, EXECUTABLE_PATH, ICONTEXT, CATEGORY, 
                         APP_TYPE, MINIMUM_ROLE, IS_ENABLED, SORT_ORDER, CREATED_DATE, 
                         MODIFIED_DATE, CREATED_BY, REQUIRED_GROUPS) 
VALUES ('Notepad', 'Text Editor', 'notepad.exe', '📝', 'Utilities', 1, 2, TRUE, 2, 
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'System', '[]');

INSERT INTO APPLICATIONS (NAME, DESCRIPTION, EXECUTABLE_PATH, ICONTEXT, CATEGORY, 
                         APP_TYPE, MINIMUM_ROLE, IS_ENABLED, SORT_ORDER, CREATED_DATE, 
                         MODIFIED_DATE, CREATED_BY, REQUIRED_GROUPS) 
VALUES ('Google', 'Google Search', 'https://www.google.com', '🌐', 'Web', 2, 2, TRUE, 3, 
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'System', '[]');

INSERT INTO APPLICATIONS (NAME, DESCRIPTION, EXECUTABLE_PATH, ICONTEXT, CATEGORY, 
                         APP_TYPE, MINIMUM_ROLE, IS_ENABLED, SORT_ORDER, CREATED_DATE, 
                         MODIFIED_DATE, CREATED_BY, REQUIRED_GROUPS) 
VALUES ('Control Panel', 'Windows Control Panel', 'control.exe', '⚙️', 'System', 1, 1, TRUE, 4, 
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'System', '["LauncherPowerUsers", "LauncherAdmins"]');

INSERT INTO APPLICATIONS (NAME, DESCRIPTION, EXECUTABLE_PATH, ICONTEXT, CATEGORY, 
                         APP_TYPE, MINIMUM_ROLE, IS_ENABLED, SORT_ORDER, CREATED_DATE, 
                         MODIFIED_DATE, CREATED_BY, REQUIRED_GROUPS) 
VALUES ('Command Prompt', 'Windows Command Line', 'cmd.exe', '💻', 'System', 1, 2, TRUE, 5, 
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'System', '[]');

COMMIT;

-- Проверяем созданные таблицы
SELECT 'Firebird 5.0 embedded database v1.0.0.001 created successfully!' AS STATUS FROM RDB$DATABASE;

/*
===== ИНСТРУКЦИИ ПО ИСПОЛЬЗОВАНИЮ FIREBIRD 5.0 EMBEDDED =====

1. СОЗДАНИЕ БД:
   - Убедитесь что папка C:\WindowsLauncher\Data\ существует
   - Выполните: isql -i create_firebird_embedded_v1.0.0.001_FIXED.sql

2. НАСТРОЙКА ПРИЛОЖЕНИЯ:
   {
     "DatabaseType": "Firebird",
     "DatabasePath": "C:\\WindowsLauncher\\Data\\launcher_embedded.fdb",
     "Username": "SYSDBA",
     "Password": "KDV_Launcher_2025!",
     "ConnectionMode": "Embedded",
     "Charset": "UTF8",
     "Dialect": 3,
     "ConnectionTimeout": 15
   }

ВАЖНЫЕ ОСОБЕННОСТИ EMBEDDED РЕЖИМА:
- Не требует установки Firebird Server
- Файл БД доступен только одному процессу
- Идеально для локальных установок
- Все возможности Firebird 5.0 доступны
- Автоматическое управление подключениями

КЛЮЧЕВЫЕ УЛУЧШЕНИЯ ДЛЯ FIREBIRD 5.0:
- IDENTITY колонки вместо генераторов
- BLOB SUB_TYPE TEXT для текстовых полей
- Оптимизированные индексы
- Современный синтаксис SQL
*/