-- ===== create_firebird_embedded_v1.0.0.001.sql =====
-- Скрипт для создания EMBEDDED Firebird базы данных v1.0.0.001
-- Для локальных установок с файловой БД
-- Использование: isql -user SYSDBA -password masterkey -i create_firebird_embedded_v1.0.0.001.sql

-- 1. Создание embedded базы данных
CREATE DATABASE 'C:\WindowsLauncher\Data\launcher_embedded.fdb' 
PAGE_SIZE 8192
USER 'SYSDBA' 
PASSWORD 'KDV_Launcher_2025!'
DEFAULT CHARACTER SET UTF8;

-- Подключение к созданной БД
CONNECT 'C:\WindowsLauncher\Data\launcher_embedded.fdb' 
USER 'SYSDBA' 
PASSWORD 'KDV_Launcher_2025!';

-- ===== СОЗДАНИЕ ГЕНЕРАТОРОВ =====
CREATE GENERATOR GEN_USERS_ID;
SET GENERATOR GEN_USERS_ID TO 1;

CREATE GENERATOR GEN_APPLICATIONS_ID;
SET GENERATOR GEN_APPLICATIONS_ID TO 1;

CREATE GENERATOR GEN_USER_SETTINGS_ID;
SET GENERATOR GEN_USER_SETTINGS_ID TO 1;

CREATE GENERATOR GEN_AUDIT_LOGS_ID;
SET GENERATOR GEN_AUDIT_LOGS_ID TO 1;

CREATE GENERATOR GEN_MIGRATION_HISTORY_ID;
SET GENERATOR GEN_MIGRATION_HISTORY_ID TO 1;

-- ===== СОЗДАНИЕ ТАБЛИЦ =====

-- Таблица пользователей
CREATE TABLE USERS (
    ID INTEGER NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    DISPLAY_NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(255) DEFAULT '',
    ROLE INTEGER NOT NULL DEFAULT 2,
    IS_ACTIVE SMALLINT NOT NULL DEFAULT 1,
    IS_SERVICE_ACCOUNT SMALLINT NOT NULL DEFAULT 0,
    PASSWORD_HASH VARCHAR(500) DEFAULT '',
    SALT VARCHAR(500) DEFAULT '',
    CREATED_AT TIMESTAMP NOT NULL,
    LAST_LOGIN_AT TIMESTAMP,
    LAST_ACTIVITY_AT TIMESTAMP,
    FAILED_LOGIN_ATTEMPTS INTEGER NOT NULL DEFAULT 0,
    IS_LOCKED SMALLINT NOT NULL DEFAULT 0,
    LOCKOUT_END TIMESTAMP,
    LAST_PASSWORD_CHANGE TIMESTAMP,
    GROUPS_JSON VARCHAR(2000) DEFAULT '[]',
    SETTINGS_JSON VARCHAR(4000) DEFAULT '{}',
    METADATA_JSON VARCHAR(2000) DEFAULT '{}',
    AUTHENTICATION_TYPE INTEGER NOT NULL DEFAULT 0,
    DOMAIN_USERNAME VARCHAR(100) DEFAULT '',
    LAST_DOMAIN_SYNC TIMESTAMP,
    IS_LOCAL_USER SMALLINT NOT NULL DEFAULT 1,
    ALLOW_LOCAL_LOGIN SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME)
);

-- Таблица приложений
CREATE TABLE APPLICATIONS (
    ID INTEGER NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(500),
    EXECUTABLE_PATH VARCHAR(1000) NOT NULL,
    ARGUMENTS VARCHAR(500),
    WORKING_DIRECTORY VARCHAR(1000),
    ICON_PATH VARCHAR(1000),
    ICONTEXT VARCHAR(50) DEFAULT '📱',
    CATEGORY VARCHAR(100),
    APP_TYPE INTEGER NOT NULL DEFAULT 0,
    MINIMUM_ROLE INTEGER NOT NULL DEFAULT 2,
    IS_ENABLED SMALLINT NOT NULL DEFAULT 1,
    SORT_ORDER INTEGER NOT NULL DEFAULT 0,
    CREATED_DATE TIMESTAMP NOT NULL,
    MODIFIED_DATE TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(100),
    REQUIRED_GROUPS BLOB SUB_TYPE 1 DEFAULT '[]',
    CONSTRAINT PK_APPLICATIONS PRIMARY KEY (ID)
);

-- Таблица настроек пользователей
CREATE TABLE USER_SETTINGS (
    ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    THEME VARCHAR(50) DEFAULT 'Light',
    ACCENT_COLOR VARCHAR(50) DEFAULT 'Blue',
    TILE_SIZE INTEGER DEFAULT 150,
    SHOW_CATEGORIES SMALLINT DEFAULT 1,
    DEFAULT_CATEGORY VARCHAR(100) DEFAULT 'All',
    AUTO_REFRESH SMALLINT DEFAULT 1,
    REFRESH_INTERVAL_MINUTES INTEGER DEFAULT 30,
    SHOW_DESCRIPTIONS SMALLINT DEFAULT 1,
    HIDDEN_CATEGORIES BLOB SUB_TYPE 1 DEFAULT '[]',
    LAST_MODIFIED TIMESTAMP NOT NULL,
    CONSTRAINT PK_USER_SETTINGS PRIMARY KEY (ID),
    CONSTRAINT FK_USER_SETTINGS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Таблица аудита
CREATE TABLE AUDIT_LOGS (
    ID INTEGER NOT NULL,
    USER_ID INTEGER,
    USERNAME VARCHAR(100) NOT NULL,
    ACTION VARCHAR(100) NOT NULL,
    APPLICATION_NAME VARCHAR(200),
    DETAILS BLOB SUB_TYPE 1,
    TIMESTAMP_UTC TIMESTAMP NOT NULL,
    SUCCESS SMALLINT NOT NULL DEFAULT 1,
    ERROR_MESSAGE VARCHAR(1000),
    COMPUTER_NAME VARCHAR(100),
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(500),
    METADATA_JSON BLOB SUB_TYPE 1 DEFAULT '{}',
    CONSTRAINT PK_AUDIT_LOGS PRIMARY KEY (ID),
    CONSTRAINT FK_AUDIT_LOGS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE SET NULL
);

-- Таблица версий БД
CREATE TABLE DATABASE_VERSION (
    VERSION VARCHAR(20) NOT NULL,
    APPLIED_AT TIMESTAMP NOT NULL,
    APPLICATION_VERSION VARCHAR(20),
    CONSTRAINT PK_DATABASE_VERSION PRIMARY KEY (VERSION)
);

-- Таблица истории миграций
CREATE TABLE MIGRATION_HISTORY (
    ID INTEGER NOT NULL,
    VERSION VARCHAR(20) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION BLOB SUB_TYPE 1,
    APPLIED_AT TIMESTAMP NOT NULL,
    ROLLBACK_SCRIPT BLOB SUB_TYPE 1,
    CONSTRAINT PK_MIGRATION_HISTORY PRIMARY KEY (ID)
);

-- ===== ТРИГГЕРЫ =====
CREATE TRIGGER TRG_USERS_ID FOR USERS
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_USERS_ID, 1);
END;

CREATE TRIGGER TRG_APPLICATIONS_ID FOR APPLICATIONS
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_APPLICATIONS_ID, 1);
END;

CREATE TRIGGER TRG_USER_SETTINGS_ID FOR USER_SETTINGS
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_USER_SETTINGS_ID, 1);
END;

CREATE TRIGGER TRG_AUDIT_LOGS_ID FOR AUDIT_LOGS
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_AUDIT_LOGS_ID, 1);
END;

CREATE TRIGGER TRG_MIGRATION_HISTORY_ID FOR MIGRATION_HISTORY
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_MIGRATION_HISTORY_ID, 1);
END;

-- ===== ИНДЕКСЫ =====
CREATE INDEX IDX_USERS_USERNAME ON USERS(USERNAME);
CREATE INDEX IDX_USERS_ROLE ON USERS(ROLE);
CREATE INDEX IDX_APPLICATIONS_NAME ON APPLICATIONS(NAME);
CREATE INDEX IDX_APPLICATIONS_CATEGORY ON APPLICATIONS(CATEGORY);
CREATE INDEX IDX_APPLICATIONS_ENABLED ON APPLICATIONS(IS_ENABLED);
CREATE INDEX IDX_USER_SETTINGS_USER_ID ON USER_SETTINGS(USER_ID);
CREATE INDEX IDX_AUDIT_LOGS_TIMESTAMP ON AUDIT_LOGS(TIMESTAMP_UTC);
CREATE INDEX IDX_AUDIT_LOGS_USER_ID ON AUDIT_LOGS(USER_ID);
CREATE INDEX IDX_MIGRATION_HISTORY_VERSION ON MIGRATION_HISTORY(VERSION);

-- ===== НАЧАЛЬНЫЕ ДАННЫЕ =====
INSERT INTO DATABASE_VERSION (VERSION, APPLIED_AT, APPLICATION_VERSION) 
VALUES ('1.0.0.001', CURRENT_TIMESTAMP, '1.0.0');

INSERT INTO MIGRATION_HISTORY (VERSION, NAME, DESCRIPTION, APPLIED_AT) 
VALUES ('1.0.0.001', 'InitialSchema', 'Create initial database schema with all tables and indexes', CURRENT_TIMESTAMP);

-- Базовый пользователь (guest) для первоначального доступа
-- ПРИМЕЧАНИЕ: Пользователь 'serviceadmin' для администрирования создается автоматически
-- сервисом AuthenticationConfigurationService при первом запуске через auth-config.json
INSERT INTO USERS (USERNAME, DISPLAY_NAME, EMAIL, ROLE, IS_ACTIVE, IS_SERVICE_ACCOUNT, PASSWORD_HASH, SALT, CREATED_AT, AUTHENTICATION_TYPE, DOMAIN_USERNAME, IS_LOCAL_USER, ALLOW_LOCAL_LOGIN, FAILED_LOGIN_ATTEMPTS, IS_LOCKED, GROUPS_JSON, SETTINGS_JSON, METADATA_JSON) 
VALUES ('guest', 'Guest User', 'guest@local', 2, 1, 0, '', '', CURRENT_TIMESTAMP, 0, '', 1, 0, 0, 0, '[]', '{}', '{}');

-- Базовые приложения
INSERT INTO APPLICATIONS (NAME, DESCRIPTION, EXECUTABLE_PATH, ICONTEXT, CATEGORY, APP_TYPE, MINIMUM_ROLE, IS_ENABLED, SORT_ORDER, CREATED_DATE, MODIFIED_DATE, CREATED_BY, REQUIRED_GROUPS) 
VALUES ('Calculator', 'Windows Calculator', 'calc.exe', '🧮', 'Utilities', 0, 2, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'System', '[]');

INSERT INTO APPLICATIONS (NAME, DESCRIPTION, EXECUTABLE_PATH, ICONTEXT, CATEGORY, APP_TYPE, MINIMUM_ROLE, IS_ENABLED, SORT_ORDER, CREATED_DATE, MODIFIED_DATE, CREATED_BY, REQUIRED_GROUPS) 
VALUES ('Notepad', 'Text Editor', 'notepad.exe', '📝', 'Utilities', 0, 2, 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'System', '[]');

INSERT INTO APPLICATIONS (NAME, DESCRIPTION, EXECUTABLE_PATH, ICONTEXT, CATEGORY, APP_TYPE, MINIMUM_ROLE, IS_ENABLED, SORT_ORDER, CREATED_DATE, MODIFIED_DATE, CREATED_BY, REQUIRED_GROUPS) 
VALUES ('Google', 'Google Search', 'https://www.google.com', '🌐', 'Web', 1, 2, 1, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'System', '[]');

INSERT INTO APPLICATIONS (NAME, DESCRIPTION, EXECUTABLE_PATH, ICONTEXT, CATEGORY, APP_TYPE, MINIMUM_ROLE, IS_ENABLED, SORT_ORDER, CREATED_DATE, MODIFIED_DATE, CREATED_BY, REQUIRED_GROUPS) 
VALUES ('Control Panel', 'Windows Control Panel', 'control.exe', '⚙️', 'System', 0, 1, 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'System', '["LauncherPowerUsers", "LauncherAdmins"]');

INSERT INTO APPLICATIONS (NAME, DESCRIPTION, EXECUTABLE_PATH, ICONTEXT, CATEGORY, APP_TYPE, MINIMUM_ROLE, IS_ENABLED, SORT_ORDER, CREATED_DATE, MODIFIED_DATE, CREATED_BY, REQUIRED_GROUPS) 
VALUES ('Command Prompt', 'Windows Command Line', 'cmd.exe', '💻', 'System', 0, 2, 1, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'System', '[]');

COMMIT;

-- Проверка
SELECT 'Embedded Firebird database v1.0.0.001 created successfully!' AS STATUS FROM RDB$DATABASE;
SELECT * FROM DATABASE_VERSION;
SELECT COUNT(*) AS APP_COUNT FROM APPLICATIONS;