using System.ComponentModel.DataAnnotations;

namespace WindowsLauncher.Core.Models
{
    /// <summary>
    /// Определение категории приложений
    /// </summary>
    public class CategoryDefinition
    {
        /// <summary>
        /// Уникальный ключ категории
        /// </summary>
        [Required]
        public string Key { get; set; } = string.Empty;

        /// <summary>
        /// Имя по умолчанию (на английском)
        /// </summary>
        [Required]
        public string DefaultName { get; set; } = string.Empty;

        /// <summary>
        /// Ключ локализации для ресурсов
        /// </summary>
        public string LocalizationKey { get; set; } = string.Empty;

        /// <summary>
        /// Иконка FontAwesome
        /// </summary>
        public string Icon { get; set; } = "FolderOpen";

        /// <summary>
        /// Цвет категории в hex формате
        /// </summary>
        public string Color { get; set; } = "#666666";

        /// <summary>
        /// Порядок сортировки
        /// </summary>
        public int SortOrder { get; set; } = 999;

        /// <summary>
        /// Системная категория (не может быть удалена)
        /// </summary>
        public bool IsSystem { get; set; } = false;

        /// <summary>
        /// Видимость категории
        /// </summary>
        public bool IsVisible { get; set; } = true;

        /// <summary>
        /// Создана автоматически из приложений
        /// </summary>
        public bool IsAutoGenerated { get; set; } = false;

        /// <summary>
        /// Дата создания
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        /// <summary>
        /// Дата последнего изменения
        /// </summary>
        public DateTime LastModified { get; set; } = DateTime.Now;
    }
}